---
- name: Install Docker 
  hosts: all
  become: yes
 
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
 
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
 
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=arm64] https://download.docker.com/linux/debian bookworm stable
        state: present
 
    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
 
    - name: Create Docker Group     
      group:
        name: "docker"
        state: present 
    - name: Add user to group 
      user:
        name: "dbarnum"
        group: "docker"
        append: yes    
        
    - name: Start Docker service
      service:
        name: docker
        state: started
